AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - db/schema.rb
    - db/seeds.rb
    - node_modules/**/*
    - vendor/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
    - Gemfile
    - Rakefile
    - Guardfile

